import Head from "next/head";
import Footer from "./Shared/Footer";
import Header from "./Shared/Header";

function Layout({ showHeader = true, showFooter = true, children }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showHeader && <Header />}
      <main>
        {children}
      </main>
      {showFooter && <Footer />}
    </div>
  );
}

export default Layout;
