import Head from 'next/head';
import { Footer2 } from './Shared/Footer2';
import Header from './Shared/Header';

function Layout({ showHeader = true, showFooter = true, userLoggedIn, children }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showHeader && <Header userLoggedIn={userLoggedIn} />} {/* Pass userLoggedIn prop to Header */}
      <main>{children}</main>
      {showFooter && <Footer2 />}
    </div>
  );
}

export default Layout;
